# Generated by Django 5.0 on 2023-12-21 22:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=200)),
                ('cargo_abreviado', models.CharField(max_length=3)),
                ('empresa_id', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
            },
        ),
    ]
