# Generated by Django 5.0 on 2023-12-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_remove_cargos_cargo_abreviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos',
            name='id',
            field=models.UUIDField(default='<function uuid4 at 0x7fd939891440>', editable=False, primary_key=True, serialize=False),
        ),
    ]
