# Generated by Django 5.0 on 2023-12-22 15:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0003_alter_cargos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
