# Generated by Django 5.0 on 2023-12-22 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0004_alter_cargos_id'),
        ('empresas', '0005_alter_empresas_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos',
            name='empresa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresas'),
        ),
    ]
