# Generated by Django 5.0 on 2023-12-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0005_alter_cargos_empresa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargos',
            old_name='empresa_id',
            new_name='empresa',
        ),
    ]
