# Generated by Django 5.0 on 2023-12-26 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0001_initial'),
        ('empresas', '0001_initial'),
        ('payments', '0001_initial'),
        ('servicos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('deleted', models.BooleanField(default=False)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField(blank=True, default=None, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=None)),
                ('cep', models.CharField(blank=True, max_length=8, null=None)),
                ('telefone', models.CharField(max_length=11)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresas')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payments')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servicos')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
            bases=('authenticate.user', models.Model),
        ),
    ]
