# Generated by Django 5.0 on 2023-12-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=None),
        ),
    ]
