# Generated by Django 5.0 on 2023-12-27 18:07

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(default='', max_length=200)),
                ('nome_fantasia', models.CharField(default='', max_length=200)),
                ('cnpj', models.CharField(default='', max_length=14)),
                ('telefone', models.CharField(default='', max_length=11)),
                ('user_alteracao', models.CharField(blank=True, max_length=200, null=None)),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime(2023, 12, 27, 15, 7, 34, 458749))),
                ('data_atualizacao', models.DateTimeField(default=datetime.datetime(2023, 12, 27, 15, 7, 34, 458766))),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
            },
        ),
    ]
