# Generated by Django 5.0 on 2023-12-20 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 18, 10, 22, 938233)),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 18, 10, 22, 938220)),
        ),
    ]
