# Generated by Django 4.2.7 on 2023-12-01 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 17, 35, 47, 491249)),
        ),
    ]
