# Generated by Django 5.0 on 2024-01-16 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresas_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 17, 18, 23, 384487)),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 17, 18, 23, 384473)),
        ),
    ]
