# Generated by Django 5.0 on 2023-12-22 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresas_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 12, 3, 24, 439666)),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 12, 3, 24, 439651)),
        ),
    ]
