# Generated by Django 4.2.7 on 2023-12-04 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_alter_empresas_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 18, 6, 11, 854061)),
        ),
    ]
