# Generated by Django 4.2.7 on 2023-12-08 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('descricao', models.CharField(max_length=100)),
                ('custo', models.IntegerField()),
                ('preco_revenda', models.IntegerField()),
                ('empresas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresas')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiais',
                'db_table': 'materiais',
            },
        ),
    ]
