# Generated by Django 5.0 on 2024-01-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiais',
            old_name='empresa',
            new_name='empresa_id',
        ),
    ]
