# Generated by Django 4.2.7 on 2023-12-08 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiais',
            name='deleted',
        ),
    ]
