# Generated by Django 5.0 on 2023-12-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
