# Generated by Django 4.2.7 on 2023-12-01 20:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_alter_empresas_data_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime(2023, 12, 1, 17, 35, 47, 491734))),
                ('data_nascimento', models.DateTimeField(default=None)),
                ('ativo', models.BooleanField(default=True)),
                ('funcao', models.CharField(choices=[('ADM', 'Administrativo'), ('RECP', 'Recepcao'), ('TAT', 'Tatuador'), ('BODY', 'Body Piercing'), ('MIC', 'Micropigmentação')], max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('empresa_id', models.CharField(max_length=256)),
                ('empresas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresas')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
