# Generated by Django 5.0 on 2023-12-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
    ]
