# Generated by Django 4.2.7 on 2023-12-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuarios_managers_remove_usuarios_ativo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='data_nascimento',
            field=models.DateField(default=None),
        ),
    ]
