# Generated by Django 5.0 on 2023-12-26 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0001_initial'),
        ('clientes', '0001_initial'),
        ('detalhe_servico', '0001_initial'),
        ('empresas', '0001_initial'),
        ('payments', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='detalhes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detalhe_servico.detalhes'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresas'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payments'),
        ),
    ]
