# Generated by Django 5.0 on 2023-12-26 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='taxa_maquina',
        ),
    ]
