# Generated by Django 4.2.7 on 2023-11-28 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 17, 42, 35, 608990)),
        ),
    ]
