# Generated by Django 5.0 on 2023-12-27 18:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiais', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalhes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=0)),
                ('valor_total', models.CharField(default='0', max_length=100)),
                ('lucro_estudio', models.CharField(blank=True, default='0', max_length=100, null=None)),
                ('lucro_colaborador', models.CharField(blank=True, default='0', max_length=100, null=None)),
                ('materiais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiais.materiais')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servicos')),
            ],
            options={
                'verbose_name': 'Detalhamento',
                'verbose_name_plural': 'Detalhamentos',
                'db_table': 'detalhes',
            },
        ),
    ]
