# Generated by Django 5.0 on 2023-12-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalhe_servico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalhes',
            name='taxa_revenda',
        ),
    ]
